#!/bin/sh
# Copyright 2022 Gérald Kerma

[ -n "$INTERFACE" ] || exit 0

[ "$ACTION" = ifup ] && {
    if ! /etc/init.d/wanmonitor enabled || [ "$(uci get "wanmonitor.@wanmonitor[0].wan_primary")" != "$INTERFACE" ]; then
        exit 0
    fi

    logger -t wanmonitor "Starting wanmonitor due to $ACTION of $INTERFACE ($DEVICE)"

    /etc/init.d/wanmonitor restart
}

[ "$ACTION" = ifdown ] && {
##    /etc/init.d/wanmonitor stop
}
